### ISSUE TITLE
decide on process for enabling gift subscriptions

### ISSUE THREAD

**Issue by davidmooreppf** [yescomment/bh-flaminghydra-ghosttheme#1]
Do you recommend we do this January 2022 [process](https://forum.ghost.org/t/how-to-add-member-to-subscription-plan-manually/27745/5) involving Stripe? This apparently would set users up with a reminder email through Stripe before it expires.

Or just a [manual process](https://forum.ghost.org/t/ability-for-the-members-to-gift-content/14752/4) if needed, and set up reminders for our team to email folks a year out from when they're added.

**Comment by davidmooreppf** [comment]
Super-basic Donorbox embed [here](https://flaminghydra.com/gift-subscriptions/) on a new page.

After you chat with Outpost we'll decide if we'll link that page.

The donorbox login is thebrickhousecoooperative@gmail and a password coming over secure.

**Comment by unitof** [comment]
Decided Outpost, setting up once we do BIG IMPORT!
