### ISSUE TITLE
BIG IMPORT

### ISSUE THREAD

**Issue by unitof** [yescomment/bh-flaminghydra-ghosttheme#13]
- [ ] Figure out what to do with active Stripe WITH KS/DonorBox comps
  - [ ] Might not matter and/or need to be done via Stripe coupons or Ghost comps: see https://github.com/yescomment/bh-flaminghydra-ghostconfig/blob/main/Ghost%20Import%20Findings.md#test-006-comping-vs-not-comping-existing-active-stripe-subscribers

## Edge cases
- [ ] dfmoskovitz@gmail.com may need to be manually reset to Founding Member (was victim of test 004, deleting now)
### Both active Stripe & Kickstarter/DonorBox
- [ ] me@shawnritchie.com
- [ ] christopher.lay@gmail.com
- [ ] a.a.muto@gmail.com
- [ ] aelbein@gmail.com
- [ ] jasonblinkins@gmail.com
- [ ] ksmoker@gmail.com
- [ ] smithczach@gmail.com
- [ ] sari.botton@gmail.com
- [ ] tycheng@gmail.com
- [ ] rshiggin@protonmail.com
- [ ] whetstone@gmail.com
- [ ] jgolick@hey.com
- [ ] ross.noren@gmail.com
- [ ] There are [others](https://docs.google.com/spreadsheets/d/1kRzxXjk_dnhFs4CVqflhEfeL0ILBjXaRpy4e2BoajCo/edit#gid=0), should script it out

See also:
https://github.com/yescomment/bh-flaminghydra-ghostconfig/blob/main/Ghost%20Import%20Findings.md

**Comment by hiyasw** [comment]
Yay! Also wondering if there was a mass import issue here: tpeyer@gmail.com was added as "Free" but he is a Donor Box subscriber. I gave him a comped subscription for a year. screenshot attached! [Screenshot 2024-01-30 at 5 19 51 PM](https://github.com/yescomment/bh-flaminghydra-ghosttheme/assets/134038577/dded38d5-2e5b-45e5-9e87-b90a0aa66781)

**Comment by unitof** [comment]
Odd, the Donorbox users above and below tpeyer were properly comped, so not sure. Hoping just a fluke, closing for now.
