### ISSUE TITLE
supporting Free Signups for very-periodic emails 

### ISSUE THREAD

**Issue by davidmooreppf** [yescomment/bh-flaminghydra-ghosttheme#2]
I reckon we may have a free signup option in our Portal, dunno. 

I asked a question over at [Ghost Forums](https://forum.ghost.org/t/are-all-free-signups-disallowed-when-option-is-removed-from-portal/43311) about the Sludge issue I discovered with surprise this evening, viz. how the free signup URL does not function anymore when removed from portal.

**Comment by unitof** [comment]
This is actually mandatory (as this is what lapsed subscribers drop to). We can decide later how prominent the "Free" signup option is though.
