### ISSUE TITLE
Author page Maria feedback

### ISSUE THREAD

**Issue by unitof** [yescomment/bh-flaminghydra-ghosttheme#20]
- [x] Remove reading times
- [ ] Remove "appears in" ([discussion](https://brickhousecooperative.slack.com/archives/C05QSLVBJBA/p1705433780526079?thread_ts=1705428126.508089&cid=C05QSLVBJBA))
- [x] Move announcement to bottom ([confirmed](https://brickhousecooperative.slack.com/archives/C05QSLVBJBA/p1705428206035299))
- [ ] Document how to set announcement, link, bio

**Comment by davidmooreppf** [comment]
When we have our check-in tomorrow at 11am ET, we'll see if the page layout and Puriya design on these is ready to check in. The editors are hoping for the design to be in place.
