### ISSUE TITLE
add featured image for homepage, for social sharing cards

### ISSUE THREAD

**Issue by davidmooreppf** [yescomment/bh-flaminghydra-ghosttheme#34]
People will share homepage link, so it needs an image for preview cards. 

<img width="580" alt="Screen Shot 2024-01-29 at 4 32 57 PM" src="https://github.com/yescomment/bh-flaminghydra-ghosttheme/assets/116819/a96ba61a-8f76-4a37-bba0-0e3daee9a60b">

**Comment by unitof** [comment]
Maria and Shirley now familiar with this system
