### ISSUE TITLE
add Paypal button to /donate page

### ISSUE THREAD

**Issue by davidmooreppf** [yescomment/bh-flaminghydra-ghosttheme#38]
Currently only has the Outpost form, but some folks won't want to donate with a credit card, they'll want to use a Paypal balance.

I don't know the associated Paypal account for the BH, we'll get that from Shirley and Maria.

**Comment by unitof** [comment]
@davidmooreppf see https://flaminghydracom.outpost.pub/home#/tip-button—need a PayPal Business Account.

**Comment by unitof** [comment]
This is supported by Outpost. Can be set up with any PayPal account. I think even personal or business.

But need to keep in mind receiving fees and who's handling.

Closing for now. @davidmooreppf says we're gonna punt.
