### ISSUE TITLE
check homepage post image sizes in FF

### ISSUE THREAD

**Issue by davidmooreppf** [yescomment/bh-flaminghydra-ghosttheme#41]
Homepage posts are funny in Firefox 122 on my Mac 12.6.3; check image class article cover

<img width="953" alt="Screen Shot 2024-01-31 at 11 45 13 AM" src="https://github.com/yescomment/bh-flaminghydra-ghosttheme/assets/116819/f7aa7c45-e3ab-468d-9a78-2bf98a5fe6d8">

**Comment by unitof** [comment]
Looking now. Related to previous fix, trying to wrap in a single link rather than having 2.

**Comment by unitof** [comment]
Weird, I don't see.

It was like this briefly for me yesterday but I fixed that.

What browser and when was this taken? @davidmooreppf

**Comment by davidmooreppf** [comment]
Firefox 122 on my Mac 12.6.3

**Comment by unitof** [comment]
Aha, can replicate in Firefox. On it.
