### ISSUE TITLE
instructions for spaces after preview text

### ISSUE THREAD

**Issue by davidmooreppf** [yescomment/bh-flaminghydra-ghosttheme#43]
In our Slack channel, Maria asked about how to prevent Issue email subject headings from repeating Flaming Hydra. 

In Sludge's ghost (different theme), I discovered the Excerpt character limit is 300. How it breaks is really weird (below)... there are spaces after the text "adding spaces" but they're not respected in the web browser's gmail view. 

So, it's for us to communicate the instructions on pasting extra spaces somehow. 

<img width="426" alt="Screen Shot 2024-01-31 at 3 06 25 PM" src="https://github.com/yescomment/bh-flaminghydra-ghosttheme/assets/116819/1b1d2a55-0365-4ae3-a747-1b43dc80fffd">

<img width="653" alt="Screen Shot 2024-01-31 at 3 06 20 PM" src="https://github.com/yescomment/bh-flaminghydra-ghosttheme/assets/116819/4db45b97-bcb1-40ee-9587-fa9cf2f893fe">

**Comment by davidmooreppf** [comment]
Currently looks like this in gmail desktop 

<img width="972" alt="Screen Shot 2024-02-22 at 10 11 36 AM" src="https://github.com/yescomment/bh-flaminghydra-ghosttheme/assets/116819/66a8e41d-873e-419a-ad5e-02a387968c66">

**Comment by unitof** [comment]
Can't change email templates without self-hosting, so this would be upstream request to Ghost (or thing we code ourselves).

Generally, let's avoid trying to hijack email providers. Gaming Gmail's preview text was always kind of a slimy hack imo.
