### ISSUE TITLE
Add socials links on homepage

### ISSUE THREAD

**Issue by hiyasw** [yescomment/bh-flaminghydra-ghosttheme#53]
bsky flaminghydra.bsky.social
masto @flaminghydra@thelife.boats

**Comment by unitof** [comment]
> Jacob: cool if I just do words so I don't need to install new icons
> David: I think icons are classy
> David: well let's see what [404 does](https://404media.co)
> David: ok words are classy

Just added to [secondary navigation](https://flaminghydra.ghost.io/ghost/#/settings/navigation) (fills footer).
