### ISSUE TITLE
Add this beautiful green color somewhere

### ISSUE THREAD

**Issue by hiyasw** [yescomment/bh-flaminghydra-ghosttheme#54]
I feel alongside the pink and yellow, it really ties the colors together. 
![Screenshot 2024-02-15 at 3 22 45 PM](https://github.com/yescomment/bh-flaminghydra-ghosttheme/assets/134038577/66745660-a49c-4ef1-a299-d65d2086e8a1)

**Comment by unitof** [comment]
Noted!

**Comment by unitof** [comment]
#96ca53

**Comment by unitof** [comment]
👀 
<img width="1549" alt="49986" src="https://github.com/yescomment/bh-flaminghydra-ghosttheme/assets/2448782/63a26254-155e-412d-b70d-986223bc5827">
