### ISSUE TITLE
remove scroll from contributors box on homepage, we think

### ISSUE THREAD

**Issue by davidmooreppf** [yescomment/bh-flaminghydra-ghosttheme#55]
Maria thinks we can try removing the fh-box scroll on homepage and have it be a long box. Dunno if Puriya would like to do any tweaks around the box, in that case. 

On mobile, of course, it would be a long box below the issues list on homepage, but maybe not so long. Open to feedback.

**Comment by unitof** [comment]
Easy to make it as long as it needs to be, no scroll.

What I wanted to do was make it capped in height by the left column, but was getting mentally tricky to CSS out.

Right now it's some hacky 50% height of the page.

Anyway can do!

**Comment by davidmooreppf** [comment]
Maria asked about this today in Slack, so we should do tmw.

**Comment by unitof** [comment]
Now full page height on 2-col layout (desktop), 90% screen height on single-col layout (mobile).
![Screenshot 2024-02-29 at 2 31 24 PM](https://github.com/yescomment/bh-flaminghydra-ghosttheme/assets/2448782/1ae9031a-55b1-4409-9f6d-2fc0238b1540)

<img width="1709" alt="20868" src="https://github.com/yescomment/bh-flaminghydra-ghosttheme/assets/2448782/80654777-f6bb-4ed3-9b97-be5705b41b84">

**Comment by unitof** [comment]
Update: no more scroll!
