### ISSUE TITLE
add tags section on homepage

### ISSUE THREAD

**Issue by davidmooreppf** [yescomment/bh-flaminghydra-ghosttheme#58]
Per Maria's note in fh-editorial, time to add in tags on homepage. Over to you and Puriya.  

![image (2)](https://github.com/yescomment/bh-flaminghydra-ghosttheme/assets/116819/a8481a89-cec8-4db0-ba5a-dbe08b06c35b)

**Comment by davidmooreppf** [comment]
per Maria in Slack: MEDIA . ARTS . POLITICS . WORLD . SAMPLE TRAY .

**Comment by unitof** [comment]
## Maria [feedback](https://brickhousecooperative.slack.com/archives/C06DRJT7U0J/p1709838142044089)

- [ ] whoohooooooooooooooooooooo
- [ ] "on" not necessary
- [ ] let's make it "Free Samples"
  - [ ] put at the bottom of the list
  - [ ] in different color??
- [ ] If it's going under the contributor list, left align
  - [ ] (the whole column)
