### ISSUE TITLE
Author pages: break list of posts into two sections

### ISSUE THREAD

**Issue by unitof** [yescomment/bh-flaminghydra-ghosttheme#6]
- Standalone posts (any post with this author **not** tagged `issue`)
- “Appears in” (posts with them as listed author tagged `issue`)

## Checklist

- [ ] @PuriyaMirza design sketch
  - [ ] columns?
  - [ ] scrollable? (it'll be long)
  - [ ] where does it go on mobile layout?
- [ ] @norberthnd dev

Both reverse chronolical.

@PuriyaMirza to consult on layout/headings to clarify the differences between two for users.

**Comment by davidmooreppf** [comment]
A question from Norbert in Slack raised the issue that this would break pagination. So I've decided that the "Appears in" column is no longer needed on Author pages. (I think Maria who made the author page mockup had mentioned that column as a possible-to-have, not a must-to-have.) Sound good, strike that part?

**Comment by unitof** [comment]
Don't think much design really needs to be done here, unless @PuriyaMirza you have ideas.

No worries on pagination, we like long scrolls and ⌘-F friendly pages! Just let me know @norberthnd if Ghost has any hard limits on posts per author page because of that.

**Comment by norberthnd** [comment]
I created the separate sections:
- the first section appears as it was before, but it will not show posts tagged `issue`
- the second section appears after the bio section and shows posts tagged `issue`, with a heading 'Appears in:'
- the styling is the same for both sections, but special classes can be added in case it's needed

**Comment by unitof** [comment]
I assigned all authors to Preview Issue so we can test:

https://flaminghydra.com/preview/

And some standalone pieces:

https://flaminghydra.com/author/tom-scocca
https://flaminghydra.com/author/diana-moskovitz/

Going to close this, but @davidmooreppf @PuriyaMirza could you test for any changes we want to make to language/design and document how this works for Shirley & Maria?
