### ISSUE TITLE
Remove automatic byline at the top

### ISSUE THREAD

**Issue by hiyasw** [yescomment/bh-flaminghydra-ghosttheme#61]
Ghost is autogenerating bylines for regular 'pages' — so let's remove automatic byline for now, and we'll continue putting it in manually until we put in a firmer plan. Sorry about the confusion

**Comment by davidmooreppf** [comment]
ah I see ! Jacob can exclude Pages from that. We'll see when his time turns to FH

**Comment by hiyasw** [comment]
I think it's best to just add manually for now, since we also need to exclude Pod. I want to be able to add/remove bylines as needed without needing to reach out about doing it programmatically

**Comment by davidmooreppf** [comment]
OK, Jacob will reverse it and you can add back in to old posts. I see that the sites built by Lede — like Hell Gate and Defector and Aftermath — put author byline below hed, dek, and featured image, but other Ghost sites like 404 Media and The Lever place them more above-image. Anyway, he'll do it and ping you to add them back in.

**Comment by unitof** [comment]
I removed bylines from Pages.

Podcast posts should really be _posts_, with a `podcast` tag.

**Comment by hiyasw** [comment]
Thank you! Podcasts are currently posts, the page was for Press Room

**Comment by unitof** [comment]
The exception would be if we want a single podcast landing page, explaining the show and listing the latest episode, like flaminghydra.com/podcast.

Generally:

Posts should be timely, serial content which doesn't update other than to correct errors after posting.

Pages are evergreen content, which never changes URL but might be updated over time with short and shareable URL (FAQs, About, Podcast, etc.)

**Comment by unitof** [comment]
Just confirmed Joe's posts are. Great!

Just noting here that iframe embeds will never work in emails. Instead you'll always want to direct link to the episode, like https://roundtable.flaminghydra.com/0001

**Comment by unitof** [comment]
> Thank you! Podcasts are currently posts, the page was for Press Room

Just saw this! Thanks Shirley.
