### ISSUE TITLE
Fix search results

### ISSUE THREAD

**Issue by hiyasw** [yescomment/bh-flaminghydra-ghosttheme#71]
Not sure why nothing is coming up 
![Screenshot 2024-03-18 at 10 26 37 AM](https://github.com/yescomment/bh-flaminghydra-ghosttheme/assets/134038577/eb10aed1-2517-46a0-bbd5-c599a61c3f2b)

**Comment by davidmooreppf** [comment]
Ghost search is limited - we were surprised by how limited it is when we moved to Sludge. I had assumed it would search full content, but nope.

Per a [2022](https://ghost.org/changelog/search/) post: "The search feature indexes post titles, excerpts, authors and tags - but it does not search across post content..."

... so you'll have to tag posts as "Gaza" to find it. Maybe search will be better sometime this year, I haven't looked at that question in Ghost forums recently.

**Comment by unitof** [comment]
I can hide the search since it's pretty bland. Or look into alt search.

**Comment by hiyasw** [comment]
Yeah maria and i are good with getting rid of it for now!!

**Comment by davidmooreppf** [comment]
yeah Jacob is gonna hide search, since it's a partial experience, then will close this issue
