### ISSUE TITLE
change text on Issues page

### ISSUE THREAD

**Issue by davidmooreppf** [yescomment/bh-flaminghydra-ghosttheme#83]
Per Maria in our Slack chat, on [/issues](https://flaminghydra.com/issues/), change "An ingenious brief cooperatively-owned..." to 

With your subscription, [link] Flaming Hydra will appear as an email newsletter with short articles, essays, comics, commentary, and happenings: every weekday.. You can also read all the archived newsletters here.

**Comment by unitof** [comment]
User editable here: https://flaminghydra.ghost.io/ghost/#/tags/issues. All set.
