### ISSUE TITLE
add 'previously' and 'subsequently' nav to bottom of [issues / posts]

### ISSUE THREAD

**Issue by davidmooreppf** [yescomment/bh-flaminghydra-ghosttheme#84]
Per Maria in Editorial channel in Slack yesterday, add Previously and Subsequently nav to bottom of (well, either issues and posts or both).

**Comment by davidmooreppf** [comment]
and yeah on June 13 in our Slack channel Maria suggested again 'suggested reading' links at bottom of [issues or posts or both]. 

I know we're using a version of the Dawn theme which technically [has](https://ghost.org/themes/dawn/) a section class="related-wrapper gh-canvas" but I have no idea if we use that. 

We can just go for something here. On Issues, go for "previous" and "next" at bottom, and at posts, try the "related" section. Open to your ideas.

**Comment by unitof** [comment]
Yep, the Related Posts logic is still there, was just turned off.

All it does under the hood is get up to 5 posts with same tag though.

Just flipped it on. I can also disable it on certain post types (like issues) if we want, or change the style (so it's more like the Latest Stories block). Lmk.

https://github.com/user-attachments/assets/22e97380-c583-4e87-b363-bf57fd4d3567

**Comment by unitof** [comment]
Reference: https://ghost.org/docs/themes/helpers/prev_next_post/ (can filter by tag!)

**Comment by davidmooreppf** [comment]
Hmm, Is something in our theme preventing the related posts from showing now? This [post](https://flaminghydra.com/divine-provenance-at-the-met/) has tags art and culture, but no "you might also like" at bottom. And the slider is indeed on, in settings.

![Image](https://github.com/user-attachments/assets/ae99f2b7-77a1-4625-a8e1-878236c071c7)
