### ISSUE TITLE
redirect post URL for Trump campaign promises

### ISSUE THREAD

**Issue by davidmooreppf** [yescomment/bh-flaminghydra-ghosttheme#92]
From https://flaminghydra.com/13-real-terrifyingly-specific-trump-campaign-promises-2/ to etc.

**Comment by davidmooreppf** [comment]
Maria posted by herself today but the -2 was still added somehow. So somehow the -2 is appearing just in one browser. A curious case.

**Comment by unitof** [comment]
Seems to happen if you rename post very shortly after a draft with desired name is deleted. -2 automatically added.
